modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Chisel-Team/ConnectedTexturesMod/issues/"
license="GPL-2.0"

[[mods]]
    modId="ctm"
    version="${file.jarVersion}"
    displayName="ConnectedTexturesMod"
    displayURL="https://chisel.team/ctm"
    #logoFile="examplemod.png"
    authors="tterrag, Drullkus, minecreatr"
    description='''
    Allows resource packs to add connected textures, emissive rendering, and much more.
    '''

[[mixins]]
    config = "ctm.mixins.json"

[[dependencies.ctm]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.82-beta,)"
    ordering="NONE"
    side="BOTH"